# -*- coding: utf-8 -*-
"""09.1_Movie-Genre-Classifier-with-Multi-label-Output.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BRK31q8R24JtHigXZVBV3pDd8XlhKuxj
"""

# Importing essential libraries
import pandas as pd
import numpy as np

# Load the 'movie_metadata.tsv' dataset
movie_metadata = pd.read_csv('/content/sample_data/movie_metadata.tsv', sep='\t', header=None)

# Display the first 5 rows to verify
display(movie_metadata.head())

# Loading the 'plot_summaries.tsv' dataset
plot_summary = pd.read_csv('/content/sample_data/plot_summaries.tsv', sep='\t', header=None)

"""Exploring the dataset"""

movie_metadata.head()

movie_metadata.shape

movie_metadata.dtypes



plot_summary.shape

plot_summary.dtypes

"""Data Cleaning


• Renaming required columns from 'movie_metadata' and 'plot_summary' dataframes


• Merging 'movie_metadata' and 'plot_summary' dataframes into one


• Cleaning the 'genre' column


• Remove rows with 0 genre tags
"""

# Renaming the required columns
movie_metadata.columns = ["movie_id", 1, "movie_name", 3, 4, 5, 6, 7, "genre"]

# Renaming the required columns
plot_summary.columns = ["movie_id", "plot"]

# Merging both dataframes
df = pd.merge(movie_metadata[['movie_id', 'movie_name', 'genre']], plot_summary, on='movie_id')

df.shape

df.head()

# Cleaning the genre column
df['genre'][0]

import json
json.loads(df['genre'][0]).values()

df['genre'] = df['genre'].apply(lambda x: list(json.loads(x).values()))
df.head()

# Remove rows with 0 genre tags
print("Before removing the rows: {}".format(df.shape))
df = df[df['genre'].apply(lambda x: False if len(x)==0 else True)]
print("After removing the rows: {}".format(df.shape))

"""Data Visualization

• Different types of genre's
"""

# Importing essential libraries
import matplotlib.pyplot as plt
import seaborn as sns

# Calculating unique genres
all_genres = list()
temp = list()

def total_unique_genre(x):
  global all_genre, temp
  x = x.reset_index()
  for i in range(0, x.shape[0]):
    temp = temp + x.iloc[i, 1]

  all_genre = set(temp)
  return len(all_genre)

print('Total number of unique genres are: {}'.format(total_unique_genre(df['genre'])))

# Using FreqDist to calculate the frequency of all the genres in the dataset
from nltk.probability import FreqDist
temp_with_count = FreqDist(temp)

# Creating a dataframe of genre_count
df_genre_count = pd.DataFrame({'Genre': list(temp_with_count.keys()),
                               'Count': list(temp_with_count.values())})

# Plotting the top 50 genres
genre_top_50 = df_genre_count.sort_values(by=['Count'], ascending=False).iloc[0:50, :]
plt.figure(figsize=(7,15))
sns.barplot(x='Count', y='Genre', data=genre_top_50)
plt.xlabel('Frequency Count')
plt.ylabel('Genres')

"""Data Preprocessing

• Clean plot summary

• Remove stopwords

• Stem plot summary

• Convert Genre into Target variables using MultiLabelBinarizer

• Split dataset into train and test set

• Create features from corpus using TfidfVectorizer
"""

# Importing essential libraries
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

def plot_clean(text):
  text = re.sub(pattern='[^a-zA-Z]', repl=' ', string=text)
  text = text.lower()
  text = ' '.join(text.split())
  return text

df['clean_plot'] = df['plot'].apply(lambda x: plot_clean(x))
df[['plot', 'clean_plot']].head()

# Removing the stopwords from 'clean_plot'
stopwords_set = set(stopwords.words('english'))

def plot_stopwords(text):
  words = text.split()
  words = [word for word in words if not word in stopwords_set]
  text = ' '.join(words)
  return text

df['clean_noStopword_plot'] = df['clean_plot'].apply(lambda x: plot_stopwords(x))
df[['clean_plot', 'clean_noStopword_plot']].head()

# Stemming the words from 'clean_noStopwords_plot'
ps = PorterStemmer()

def plot_stemming(text):
  words = text.split()
  words = [ps.stem(word) for word in words]
  text = ' '.join(words)
  return text

df['clean_noStopword_stem_plot'] = df['clean_noStopword_plot'].apply(lambda x: plot_stemming(x))
df[['clean_noStopword_plot', 'clean_noStopword_stem_plot']].head()

# Convert Genre into Target variables using MultiLabelBinarizer
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
y = mlb.fit_transform(df['genre'])

X = df['clean_noStopword_stem_plot']

# Splitting the dataset into train and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

# Creating independent features using TfidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_df=0.8, max_features=10000)
X_train = tfidf.fit_transform(X_train)
X_test = tfidf.transform(X_test)

"""Model Building"""

# Logistic Regression Model
# Importing essential libraries
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier

lr = LogisticRegression()
ovr_clf = OneVsRestClassifier(lr)

# Fit model on train data
ovr_clf.fit(X_train, y_train)

# Predicting values for test set
y_pred_ovr = ovr_clf.predict(X_test)
y_pred_ovr[5]

mlb.inverse_transform(y_pred_ovr)[5]

# Model Evaluation
from sklearn.metrics import f1_score
print(f1_score(y_test, y_pred_ovr, average="micro"))

# Changing the threshold probability from 0.5 to 0.3
y_pred_prob = ovr_clf.predict_proba(X_test)
y_pred_new = (y_pred_prob >= 0.2).astype(int)

f1_score(y_test, y_pred_new, average="micro")

"""Predictions"""

# Creating a function
def predict_genre_tags(text):
    text = plot_clean(text)
    text = plot_stopwords(text)
    text = plot_stemming(text)
    text_vec = tfidf.transform([text])
    text_pred = ovr_clf.predict(text_vec)
    return mlb.inverse_transform(text_pred)

# Prediction 1
movie_name = 'Titanic (1998)'
plot_summary = "After winning a trip on the RMS Titanic during a dockside card game, American Jack Dawson spots the society girl Rose DeWitt Bukater who is on her way to Philadelphia to marry her rich snob fiancé Caledon Hockley. Rose feels helplessly trapped by her situation and makes her way to the aft deck and thinks of suicide until she is rescued by Jack. Cal is therefore obliged to invite Jack to dine at their first-class table where he suffers through the slights of his snobbish hosts. In return, he spirits Rose off to third-class for an evening of dancing, giving her the time of her life. Deciding to forsake her intended future all together, Rose asks Jack, who has made his living making sketches on the streets of Paris, to draw her in the nude wearing the invaluable blue diamond Cal has given her. Cal finds out and has Jack locked away. Soon afterwards, the ship hits an iceberg and Rose must find Jack while both must run from Cal even as the ship sinks deeper into the freezing water."
actual_genre = ['Drama', 'Romance']
predicted_genre = predict_genre_tags(plot_summary)
print('Movie: {}\nPredicted genres: {}\nActual genres: {}'.format(movie_name, predicted_genre[0], actual_genre))

# Prediction 2
movie_name = 'Avatar (2009)'
plot_summary = "On the lush alien world of Pandora live the Na'vi, beings who appear primitive but are highly evolved. Because the planet's environment is poisonous, human/Na'vi hybrids, called Avatars, must link to human minds to allow for free movement on Pandora. Jake Sully (Sam Worthington), a paralyzed former Marine, becomes mobile again through one such Avatar and falls in love with a Na'vi woman (Zoe Saldana). As a bond with her grows, he is drawn into a battle for the survival of her world."
actual_genre = ['Action', 'Adventure', 'Fantasy']
predicted_genre = predict_genre_tags(plot_summary)
print('Movie: {}\nPredicted genres: {}\nActual genres: {}'.format(movie_name, predicted_genre[0], actual_genre))

# Prediction 3
movie_name = 'Conjuring (2013)'
plot_summary = "In 1971, Carolyn and Roger Perron move their family into a dilapidated Rhode Island farm house and soon strange things start happening around it with escalating nightmarish terror. In desperation, Carolyn contacts the noted paranormal investigators, Ed and Lorraine Warren, to examine the house. What the Warrens discover is a whole area steeped in a satanic haunting that is now targeting the Perron family wherever they go. To stop this evil, the Warrens will have to call upon all their skills and spiritual strength to defeat this spectral menace at its source that threatens to destroy everyone involved."
actual_genre = ['Horror', 'Thriller']
predicted_genre = predict_genre_tags(plot_summary)
print('Movie: {}\nPredicted genres: {}\nActual genres: {}'.format(movie_name, predicted_genre[0], actual_genre))

# Prediction 4
movie_name = 'The Hangover (2009)'
plot_summary = "Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing. They make their way around the city in order to find their friend before his wedding."
actual_genre = ['Comedy']
predicted_genre = predict_genre_tags(plot_summary)
print('Movie: {}\nPredicted genres: {}\nActual genres: {}'.format(movie_name, predicted_genre[0], actual_genre))

# Prediction 5
movie_name = 'La La Land (2016)'
plot_summary = "The story of aspiring actress Mia and dedicated jazz musician Sebastian, who struggle to make ends meet while pursuing their dreams in a city known for destroying hopes and breaking hearts. With modern-day Los Angeles as the backdrop, this musical about everyday life explores what more important: a once-in-a-lifetime love or the spotlight."
actual_genre = ['Comedy', 'Drama', 'Music']
predicted_genre = predict_genre_tags(plot_summary)
print('Movie: {}\nPredicted genres: {}\nActual genres: {}'.format(movie_name, predicted_genre[0], actual_genre))

